---
# Open-ended prompts for Zero-Day Detection
# Let models reason freely without prescriptive patterns

prompts:
  ForensicAnalyst:
    system_prompt: |
      You are a cybersecurity forensics expert. Your task is to assess whether a vulnerability 
      was likely exploited as a zero-day (exploited before a patch was available).
    
    analysis_template: |
      Analyze this vulnerability:
      
      CVE ID: {cve_id}
      Vendor: {vendor}
      Product: {product}
      Description: {description}
      
      Think step by step:
      1. What does the description reveal about how this vulnerability was discovered?
      2. Are there urgency indicators or language suggesting active exploitation?
      3. Does the timeline or context suggest this was exploited before disclosure?
      
      Based on your forensic expertise, assess the likelihood this was exploited as a zero-day.
      
      Provide:
      - Prediction: [0.0-1.0 probability of zero-day exploitation]
      - Confidence: [0.0-1.0 confidence in your assessment]
      - Reasoning: [Your analysis in 2-3 sentences]

  PatternDetector:
    system_prompt: |
      You are an expert in detecting patterns in security vulnerabilities.
      Focus on identifying whether vulnerabilities show signs of zero-day exploitation.
    
    analysis_template: |
      Examine this CVE for patterns suggesting zero-day exploitation:
      
      CVE ID: {cve_id}
      Vendor: {vendor}
      Product: {product}
      Description: {description}
      
      Think step by step:
      1. What linguistic patterns are present in the description?
      2. Are there phrases commonly associated with zero-day discoveries?
      3. Does the technical detail level suggest pre-existing knowledge of exploitation?
      
      Look for patterns that distinguish zero-days from researcher-discovered vulnerabilities.
      
      Provide:
      - Prediction: [0.0-1.0]
      - Confidence: [0.0-1.0]
      - Key Patterns: [What patterns did you notice?]

  TemporalAnalyst:
    system_prompt: |
      You specialize in timeline analysis of security vulnerabilities.
      Your focus is determining if vulnerabilities were zero-days based on temporal clues.
    
    analysis_template: |
      Analyze the timeline aspects of this vulnerability:
      
      CVE ID: {cve_id}
      Year: {year}
      Vendor: {vendor}
      Product: {product}
      Description: {description}
      
      Think step by step:
      1. Does the description suggest urgency or emergency response?
      2. Are there timeline indicators (e.g., "discovered after", "already being exploited")?
      3. Does the disclosure pattern match typical zero-day or coordinated disclosure?
      
      Consider timing factors that distinguish zero-days from responsible disclosures.
      
      Provide:
      - Prediction: [0.0-1.0]
      - Confidence: [0.0-1.0]
      - Timeline Analysis: [Your temporal reasoning]

  AttributionExpert:
    system_prompt: |
      You are a threat attribution specialist. Assess whether vulnerabilities
      show characteristics of zero-day exploitation based on targeting patterns.
    
    analysis_template: |
      Evaluate this vulnerability from an attribution perspective:
      
      CVE ID: {cve_id}
      Vendor: {vendor}
      Product: {product}
      Description: {description}
      
      Think step by step:
      1. What is the strategic value of this vulnerability to threat actors?
      2. Does the target (vendor/product) suggest high-value exploitation?
      3. Are there indicators of sophisticated threat actor involvement?
      
      Consider who would benefit from keeping this vulnerability secret for zero-day use.
      
      Provide:
      - Prediction: [0.0-1.0]
      - Confidence: [0.0-1.0]
      - Attribution Analysis: [Your assessment of threat actor interest]

  MetaAnalyst:
    system_prompt: |
      You synthesize multiple perspectives to determine if vulnerabilities were zero-days.
      Zero-days are exploited before patches exist, making them extremely valuable.
    
    analysis_template: |
      Synthesize all available information about this vulnerability:
      
      CVE ID: {cve_id}
      Vendor: {vendor}
      Product: {product}
      Description: {description}
      Year: {year}
      
      Think step by step:
      1. What is the overall severity and impact of this vulnerability?
      2. Does the description language suggest discovery through active exploitation?
      3. How do all the factors combine to indicate zero-day likelihood?
      
      Consider all aspects holistically to determine if this was likely exploited as a zero-day.
      
      Provide:
      - Prediction: [0.0-1.0]
      - Confidence: [0.0-1.0]
      - Synthesis: [Your holistic analysis]
      - Key Factors: [What influenced your decision most?]

# Parameters for more creative reasoning
parameters:
  temperature: 0.3  # Slightly higher for more nuanced reasoning
  max_tokens: 500
  top_p: 0.95
  frequency_penalty: 0.0
  presence_penalty: 0.0